const sampleData = [
{
  description: 'Home in Oakland',
  host: 'Tom Brady',
  address: '123 Super Bowl Road',
  city: 'San Mateo',
  state: 'CA',
  postal_code: '94123',
  country: 'USA',
  long_lat: 4,
  seeds_required: '50',
  share_price:'10',
  seeds_count: '10',
  created_at: 4, 
  updated_at: 5, 
  image: 'home_1'
},
{
  description: 'Home in Albany',
  host: 'Brad Stevens',
  address: '123 Celtics Place',
  city: 'Albany',
  state: 'CA',
  postal_code: '94706',
  country: 'USA',
  long_lat: 4,
  seeds_required: '30',
  share_price: '20',
  seeds_count: '5',
  created_at: 1,
  updated_at: 2,
  image: 'home_2'
},
{
  description: 'Trendy Restaurant',
  host: 'Mark Twain',
  address: ' 987 Main Street',
  city: ' Oakland',
  state: 'CA',
  postal_code: '94654',
  country: 'USA',
  long_lat: 5 ,
  seeds_required: '100',
  share_price: '2',
  seeds_count: '123',
  created_at: 1,
  updated_at: 2,
  image: 'home_3'
},
{
  description: 'New Solar Company',
  host: 'Adam Smith',
  address: '321 Capitalism Lane',
  city: 'El Cerrito',
  state: 'CA',
  postal_code: '95434',
  country: 'USA',
  long_lat: 5,
  seeds_required: '500',
  share_price: '100',
  seeds_count: '4',
  created_at: 8,
  updated_at: 9,
  image: 'home_1'
},
{
  description: 'Tiny Home Needs Solar Heat',
  host: 'Michelle Obama',
  address: '543 Happy Road',
  city: 'San Francisco',
  state: 'CA',
  postal_code: '94123',
  country: 'USA',
  long_lat: 10,
  seeds_required: '200',
  share_price: '50',
  seeds_count: '23',
  created_at: 7,
  updated_at: 8,
  image: 'home_2'
},
{
  description: 'Big Home',
  host: '',
  address: '789 Open Lane',
  city: 'Berkeley',
  state: 'CA',
  postal_code: '94677',
  country: 'USA',
  long_lat: 6,
  seeds_required: '1000',
  share_price: '10',
  seeds_count: '10',
  created_at: 0,
  updated_at: 10, 
  image: 'home_3'
}
]

export default sampleData